name: ci

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run lint

            - name: Run tests
              run: npm run test
              
            - uses: actions/checkout@v2
              with:
                  fetch-depth: "0"
            - name: Bump version and push tag
              if: github.ref_name == 'main'
              uses: anothrNick/github-tag-action@1.36.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: false
                  
                  
            - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
              uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
              with:
                email: ${{ secrets.HEROKU_EMAIL }}
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: dlg-sorting-visualizer
                dockerfile_directory: ./
                dockerfile_name: Dockerfile
                docker_options: "--no-cache"
                process_type: web

   
